CREATE DATABASE QuanTS
CREATE TABLE Employees(
	ID INT NOT NULL ,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	NAME VARCHAR(20) NOT NULL ,
	PHONENUMBER varchar(20) DEFAULT NULL,
	PERMISSION VARCHAR(20)  NOT NULL,
	SALARY INT NOT NULL,
  PRIMARY KEY (ID),

);
INSERT INTO Employees VALUES (1,'admin','admin','Thai','0342964072','manager',10600000);
